### ISSUE TITLE
Add Hope automatically to sheet when rolled

### ISSUE THREAD

**Issue by k2nair** [ComfortableGreySloth/FoundryVTTDaggerheartSWB#2]
1. Character rolls duality dice
2. Result is Hope
3. System adds a hope automatically to the Character Sheet

**Comment by ComfortableGreySloth** [comment]
I made this happen before I updated the duality dice template, but because players tend to do test rolls or click on their abilities to see what they do I feel like it would end up being too much automation. Let's call this "in progress" because I can't seem to get the macro buttons into the roll flavor text, going to play with it and see what ends up the most comfortable.

**Comment by ComfortableGreySloth** [comment]
Implemented, now a public chat message appears with the increase hope, or reduce stress macros on roll with success or a crit. On a roll with fear it's a private message to the GM for increase fear.
